var testApp = angular.module('typeaheadDirectiveSample', [ 'lovTypeahead' ]);

testApp.controller('UpdateTestCtrl', function($scope) {
	$scope.address = {
		country : {
			id : 222,
			name : "Initial Value"
		}
	};
});

testApp.controller('Ctrl', function($scope) {
	$scope.country = {
		id : null,
		name : "No country selected"
	};
	$scope.dataName = "data";
	$scope.datasetIsValid = true;

	$scope.address = {
		country : null
	};

	$scope.steps = ["First country", "Secod country", "Third country", "Fourth country"];
	$scope.steps.countries = [{
		"id":7,
		"name":"Armenia"
	},
	{
		"id":8,
		"name":"Angola"
	}];

	$scope.listOfValues = {
			countries: [
			        	{
			        		"id":1,
			        		"name":"Andorra"
			        	},
			        	{
			        		"id":2,
			        		"name":"United Arab Emirates"
			        	},
			        	{
			        		"id":3,
			        		"name":"Afghanistan"
			        	},
			        	{
			        		"id":4,
			        		"name":"Antigua and Barbuda"
			        	},
			        	{
			        		"id":5,
			        		"name":"Anguilla"
			        	},
			        	{
			        		"id":6,
			        		"name":"Albania"
			        	},
			        	{
			        		"id":7,
			        		"name":"Armenia"
			        	},
			        	{
			        		"id":8,
			        		"name":"Angola"
			        	},
			        	{
			        		"id":9,
			        		"name":"Antarctica"
			        	},
			        	{
			        		"id":10,
			        		"name":"Argentina"
			        	},
			        	{
			        		"id":1,
			        		"name":"American Samoa"
			        	},
			        	{
			        		"id":1,
			        		"name":"Austria"
			        	},
			        	{
			        		"id":1,
			        		"name":"Australia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Aruba"
			        	},
			        	{
			        		"id":1,
			        		"name":"Aland"
			        	},
			        	{
			        		"id":1,
			        		"name":"Azerbaijan"
			        	},
			        	{
			        		"id":1,
			        		"name":"Bosnia and Herzegovina"
			        	},
			        	{
			        		"id":1,
			        		"name":"Barbados"
			        	},
			        	{
			        		"id":1,
			        		"name":"Bangladesh"
			        	},
			        	{
			        		"id":1,
			        		"name":"Belgium"
			        	},
			        	{
			        		"id":1,
			        		"name":"Burkina Faso"
			        	},
			        	{
			        		"id":1,
			        		"name":"Bulgaria"
			        	},
			        	{
			        		"id":1,
			        		"name":"Bahrain"
			        	},
			        	{
			        		"id":1,
			        		"name":"Burundi"
			        	},
			        	{
			        		"id":1,
			        		"name":"Benin"
			        	},
			        	{
			        		"id":1,
			        		"name":"Saint BarthĂŠlemy"
			        	},
			        	{
			        		"id":1,
			        		"name":"Bermuda"
			        	},
			        	{
			        		"id":1,
			        		"name":"Brunei"
			        	},
			        	{
			        		"id":1,
			        		"name":"Bolivia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Bonaire"
			        	},
			        	{
			        		"id":1,
			        		"name":"Brazil"
			        	},
			        	{
			        		"id":1,
			        		"name":"Bahamas"
			        	},
			        	{
			        		"id":1,
			        		"name":"Bhutan"
			        	},
			        	{
			        		"id":1,
			        		"name":"Bouvet Island"
			        	},
			        	{
			        		"id":1,
			        		"name":"Botswana"
			        	},
			        	{
			        		"id":1,
			        		"name":"Belarus"
			        	},
			        	{
			        		"id":1,
			        		"name":"Belize"
			        	},
			        	{
			        		"id":1,
			        		"name":"Canada"
			        	},
			        	{
			        		"id":1,
			        		"name":"Cocos [Keeling] Islands"
			        	},
			        	{
			        		"id":1,
			        		"name":"Congo"
			        	},
			        	{
			        		"id":1,
			        		"name":"Central African Republic"
			        	},
			        	{
			        		"id":1,
			        		"name":"Republic of the Congo"
			        	},
			        	{
			        		"id":1,
			        		"name":"Switzerland"
			        	},
			        	{
			        		"id":1,
			        		"name":"Ivory Coast"
			        	},
			        	{
			        		"id":1,
			        		"name":"Cook Islands"
			        	},
			        	{
			        		"id":1,
			        		"name":"Chile"
			        	},
			        	{
			        		"id":1,
			        		"name":"Cameroon"
			        	},
			        	{
			        		"id":1,
			        		"name":"China"
			        	},
			        	{
			        		"id":1,
			        		"name":"Colombia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Costa Rica"
			        	},
			        	{
			        		"id":1,
			        		"name":"Cuba"
			        	},
			        	{
			        		"id":1,
			        		"name":"Cape Verde"
			        	},
			        	{
			        		"id":1,
			        		"name":"Curacao"
			        	},
			        	{
			        		"id":1,
			        		"name":"Christmas Island"
			        	},
			        	{
			        		"id":1,
			        		"name":"Cyprus"
			        	},
			        	{
			        		"id":1,
			        		"name":"Czechia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Germany"
			        	},
			        	{
			        		"id":1,
			        		"name":"Djibouti"
			        	},
			        	{
			        		"id":1,
			        		"name":"Denmark"
			        	},
			        	{
			        		"id":1,
			        		"name":"Dominica"
			        	},
			        	{
			        		"id":1,
			        		"name":"Dominican Republic"
			        	},
			        	{
			        		"id":1,
			        		"name":"Algeria"
			        	},
			        	{
			        		"id":1,
			        		"name":"Ecuador"
			        	},
			        	{
			        		"id":1,
			        		"name":"Estonia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Egypt"
			        	},
			        	{
			        		"id":1,
			        		"name":"Western Sahara"
			        	},
			        	{
			        		"id":1,
			        		"name":"Eritrea"
			        	},
			        	{
			        		"id":1,
			        		"name":"Spain"
			        	},
			        	{
			        		"id":1,
			        		"name":"Ethiopia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Finland"
			        	},
			        	{
			        		"id":1,
			        		"name":"Fiji"
			        	},
			        	{
			        		"id":1,
			        		"name":"Falkland Islands"
			        	},
			        	{
			        		"id":1,
			        		"name":"Micronesia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Faroe Islands"
			        	},
			        	{
			        		"id":1,
			        		"name":"France"
			        	},
			        	{
			        		"id":1,
			        		"name":"Gabon"
			        	},
			        	{
			        		"id":1,
			        		"name":"United Kingdom"
			        	},
			        	{
			        		"id":1,
			        		"name":"Grenada"
			        	},
			        	{
			        		"id":1,
			        		"name":"Georgia"
			        	},
			        	{
			        		"id":1,
			        		"name":"French Guiana"
			        	},
			        	{
			        		"id":1,
			        		"name":"Guernsey"
			        	},
			        	{
			        		"id":1,
			        		"name":"Ghana"
			        	},
			        	{
			        		"id":1,
			        		"name":"Gibraltar"
			        	},
			        	{
			        		"id":1,
			        		"name":"Greenland"
			        	},
			        	{
			        		"id":1,
			        		"name":"Gambia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Guinea"
			        	},
			        	{
			        		"id":1,
			        		"name":"Guadeloupe"
			        	},
			        	{
			        		"id":1,
			        		"name":"Equatorial Guinea"
			        	},
			        	{
			        		"id":1,
			        		"name":"Greece"
			        	},
			        	{
			        		"id":1,
			        		"name":"South Georgia and the South Sandwich Islands"
			        	},
			        	{
			        		"id":1,
			        		"name":"Guatemala"
			        	},
			        	{
			        		"id":1,
			        		"name":"Guam"
			        	},
			        	{
			        		"id":1,
			        		"name":"Guinea-Bissau"
			        	},
			        	{
			        		"id":1,
			        		"name":"Guyana"
			        	},
			        	{
			        		"id":1,
			        		"name":"Hong Kong"
			        	},
			        	{
			        		"id":1,
			        		"name":"Heard Island and McDonald Islands"
			        	},
			        	{
			        		"id":1,
			        		"name":"Honduras"
			        	},
			        	{
			        		"id":1,
			        		"name":"Croatia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Haiti"
			        	},
			        	{
			        		"id":1,
			        		"name":"Hungary"
			        	},
			        	{
			        		"id":1,
			        		"name":"Indonesia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Ireland"
			        	},
			        	{
			        		"id":1,
			        		"name":"Israel"
			        	},
			        	{
			        		"id":1,
			        		"name":"Isle of Man"
			        	},
			        	{
			        		"id":1,
			        		"name":"India"
			        	},
			        	{
			        		"id":1,
			        		"name":"British Indian Ocean Territory"
			        	},
			        	{
			        		"id":1,
			        		"name":"Iraq"
			        	},
			        	{
			        		"id":1,
			        		"name":"Iran"
			        	},
			        	{
			        		"id":1,
			        		"name":"Iceland"
			        	},
			        	{
			        		"id":1,
			        		"name":"Italy"
			        	},
			        	{
			        		"id":1,
			        		"name":"Jersey"
			        	},
			        	{
			        		"id":1,
			        		"name":"Jamaica"
			        	},
			        	{
			        		"id":1,
			        		"name":"Jordan"
			        	},
			        	{
			        		"id":1,
			        		"name":"Japan"
			        	},
			        	{
			        		"id":1,
			        		"name":"Kenya"
			        	},
			        	{
			        		"id":1,
			        		"name":"Kyrgyzstan"
			        	},
			        	{
			        		"id":1,
			        		"name":"Cambodia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Kiribati"
			        	},
			        	{
			        		"id":1,
			        		"name":"Comoros"
			        	},
			        	{
			        		"id":1,
			        		"name":"Saint Kitts and Nevis"
			        	},
			        	{
			        		"id":1,
			        		"name":"North Korea"
			        	},
			        	{
			        		"id":1,
			        		"name":"South Korea"
			        	},
			        	{
			        		"id":1,
			        		"name":"Kuwait"
			        	},
			        	{
			        		"id":1,
			        		"name":"Cayman Islands"
			        	},
			        	{
			        		"id":1,
			        		"name":"Kazakhstan"
			        	},
			        	{
			        		"id":1,
			        		"name":"Laos"
			        	},
			        	{
			        		"id":1,
			        		"name":"Lebanon"
			        	},
			        	{
			        		"id":1,
			        		"name":"Saint Lucia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Liechtenstein"
			        	},
			        	{
			        		"id":1,
			        		"name":"Sri Lanka"
			        	},
			        	{
			        		"id":1,
			        		"name":"Liberia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Lesotho"
			        	},
			        	{
			        		"id":1,
			        		"name":"Lithuania"
			        	},
			        	{
			        		"id":1,
			        		"name":"Luxembourg"
			        	},
			        	{
			        		"id":1,
			        		"name":"Latvia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Libya"
			        	},
			        	{
			        		"id":1,
			        		"name":"Morocco"
			        	},
			        	{
			        		"id":1,
			        		"name":"Monaco"
			        	},
			        	{
			        		"id":1,
			        		"name":"Moldova"
			        	},
			        	{
			        		"id":1,
			        		"name":"Montenegro"
			        	},
			        	{
			        		"id":1,
			        		"name":"Saint Martin"
			        	},
			        	{
			        		"id":1,
			        		"name":"Madagascar"
			        	},
			        	{
			        		"id":1,
			        		"name":"Marshall Islands"
			        	},
			        	{
			        		"id":1,
			        		"name":"Macedonia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Mali"
			        	},
			        	{
			        		"id":1,
			        		"name":"Myanmar [Burma]"
			        	},
			        	{
			        		"id":1,
			        		"name":"Mongolia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Macao"
			        	},
			        	{
			        		"id":1,
			        		"name":"Northern Mariana Islands"
			        	},
			        	{
			        		"id":1,
			        		"name":"Martinique"
			        	},
			        	{
			        		"id":1,
			        		"name":"Mauritania"
			        	},
			        	{
			        		"id":1,
			        		"name":"Montserrat"
			        	},
			        	{
			        		"id":1,
			        		"name":"Malta"
			        	},
			        	{
			        		"id":1,
			        		"name":"Mauritius"
			        	},
			        	{
			        		"id":1,
			        		"name":"Maldives"
			        	},
			        	{
			        		"id":1,
			        		"name":"Malawi"
			        	},
			        	{
			        		"id":1,
			        		"name":"Mexico"
			        	},
			        	{
			        		"id":1,
			        		"name":"Malaysia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Mozambique"
			        	},
			        	{
			        		"id":1,
			        		"name":"Namibia"
			        	},
			        	{
			        		"id":1,
			        		"name":"New Caledonia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Niger"
			        	},
			        	{
			        		"id":1,
			        		"name":"Norfolk Island"
			        	},
			        	{
			        		"id":1,
			        		"name":"Nigeria"
			        	},
			        	{
			        		"id":1,
			        		"name":"Nicaragua"
			        	},
			        	{
			        		"id":1,
			        		"name":"Netherlands"
			        	},
			        	{
			        		"id":1,
			        		"name":"Norway"
			        	},
			        	{
			        		"id":1,
			        		"name":"Nepal"
			        	},
			        	{
			        		"id":1,
			        		"name":"Nauru"
			        	},
			        	{
			        		"id":1,
			        		"name":"Niue"
			        	},
			        	{
			        		"id":1,
			        		"name":"New Zealand"
			        	},
			        	{
			        		"id":1,
			        		"name":"Oman"
			        	},
			        	{
			        		"id":1,
			        		"name":"Panama"
			        	},
			        	{
			        		"id":1,
			        		"name":"Peru"
			        	},
			        	{
			        		"id":1,
			        		"name":"French Polynesia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Papua New Guinea"
			        	},
			        	{
			        		"id":1,
			        		"name":"Philippines"
			        	},
			        	{
			        		"id":1,
			        		"name":"Pakistan"
			        	},
			        	{
			        		"id":1,
			        		"name":"Poland"
			        	},
			        	{
			        		"id":1,
			        		"name":"Saint Pierre and Miquelon"
			        	},
			        	{
			        		"id":1,
			        		"name":"Pitcairn Islands"
			        	},
			        	{
			        		"id":1,
			        		"name":"Puerto Rico"
			        	},
			        	{
			        		"id":1,
			        		"name":"Palestine"
			        	},
			        	{
			        		"id":1,
			        		"name":"Portugal"
			        	},
			        	{
			        		"id":1,
			        		"name":"Palau"
			        	},
			        	{
			        		"id":1,
			        		"name":"Paraguay"
			        	},
			        	{
			        		"id":1,
			        		"name":"Qatar"
			        	},
			        	{
			        		"id":1,
			        		"name":"RĂŠunion"
			        	},
			        	{
			        		"id":1,
			        		"name":"Romania"
			        	},
			        	{
			        		"id":1,
			        		"name":"Serbia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Russia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Rwanda"
			        	},
			        	{
			        		"id":1,
			        		"name":"Saudi Arabia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Solomon Islands"
			        	},
			        	{
			        		"id":1,
			        		"name":"Seychelles"
			        	},
			        	{
			        		"id":1,
			        		"name":"Sudan"
			        	},
			        	{
			        		"id":1,
			        		"name":"Sweden"
			        	},
			        	{
			        		"id":1,
			        		"name":"Singapore"
			        	},
			        	{
			        		"id":1,
			        		"name":"Saint Helena"
			        	},
			        	{
			        		"id":1,
			        		"name":"Slovenia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Svalbard and Jan Mayen"
			        	},
			        	{
			        		"id":1,
			        		"name":"Slovakia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Sierra Leone"
			        	},
			        	{
			        		"id":1,
			        		"name":"San Marino"
			        	},
			        	{
			        		"id":1,
			        		"name":"Senegal"
			        	},
			        	{
			        		"id":1,
			        		"name":"Somalia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Suriname"
			        	},
			        	{
			        		"id":1,
			        		"name":"South Sudan"
			        	},
			        	{
			        		"id":1,
			        		"name":"SĂŁo TomĂŠ and PrĂ­ncipe"
			        	},
			        	{
			        		"id":1,
			        		"name":"El Salvador"
			        	},
			        	{
			        		"id":1,
			        		"name":"Sint Maarten"
			        	},
			        	{
			        		"id":1,
			        		"name":"Syria"
			        	},
			        	{
			        		"id":1,
			        		"name":"Swaziland"
			        	},
			        	{
			        		"id":1,
			        		"name":"Turks and Caicos Islands"
			        	},
			        	{
			        		"id":1,
			        		"name":"Chad"
			        	},
			        	{
			        		"id":1,
			        		"name":"French Southern Territories"
			        	},
			        	{
			        		"id":1,
			        		"name":"Togo"
			        	},
			        	{
			        		"id":1,
			        		"name":"Thailand"
			        	},
			        	{
			        		"id":1,
			        		"name":"Tajikistan"
			        	},
			        	{
			        		"id":1,
			        		"name":"Tokelau"
			        	},
			        	{
			        		"id":1,
			        		"name":"East Timor"
			        	},
			        	{
			        		"id":1,
			        		"name":"Turkmenistan"
			        	},
			        	{
			        		"id":1,
			        		"name":"Tunisia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Tonga"
			        	},
			        	{
			        		"id":1,
			        		"name":"Turkey"
			        	},
			        	{
			        		"id":1,
			        		"name":"Trinidad and Tobago"
			        	},
			        	{
			        		"id":1,
			        		"name":"Tuvalu"
			        	},
			        	{
			        		"id":1,
			        		"name":"Taiwan"
			        	},
			        	{
			        		"id":1,
			        		"name":"Tanzania"
			        	},
			        	{
			        		"id":1,
			        		"name":"Ukraine"
			        	},
			        	{
			        		"id":1,
			        		"name":"Uganda"
			        	},
			        	{
			        		"id":1,
			        		"name":"U.S. Minor Outlying Islands"
			        	},
			        	{
			        		"id":1,
			        		"name":"United States"
			        	},
			        	{
			        		"id":1,
			        		"name":"Uruguay"
			        	},
			        	{
			        		"id":1,
			        		"name":"Uzbekistan"
			        	},
			        	{
			        		"id":1,
			        		"name":"Vatican City"
			        	},
			        	{
			        		"id":1,
			        		"name":"Saint Vincent and the Grenadines"
			        	},
			        	{
			        		"id":1,
			        		"name":"Venezuela"
			        	},
			        	{
			        		"id":1,
			        		"name":"British Virgin Islands"
			        	},
			        	{
			        		"id":1,
			        		"name":"U.S. Virgin Islands"
			        	},
			        	{
			        		"id":1,
			        		"name":"Vietnam"
			        	},
			        	{
			        		"id":1,
			        		"name":"Vanuatu"
			        	},
			        	{
			        		"id":1,
			        		"name":"Wallis and Futuna"
			        	},
			        	{
			        		"id":1,
			        		"name":"Samoa"
			        	},
			        	{
			        		"id":1,
			        		"name":"Kosovo"
			        	},
			        	{
			        		"id":1,
			        		"name":"Yemen"
			        	},
			        	{
			        		"id":1,
			        		"name":"Mayotte"
			        	},
			        	{
			        		"id":1,
			        		"name":"South Africa"
			        	},
			        	{
			        		"id":1,
			        		"name":"Zambia"
			        	},
			        	{
			        		"id":1,
			        		"name":"Zimbabwe"
			        	}
			        ]
	};
});
